version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: jobtracker_postgres
    restart: always
    environment:
      POSTGRES_DB: jobtracker_db
      POSTGRES_USER: jobtracker_user
      POSTGRES_PASSWORD: jobtracker_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: